app:
  name: segmentation-service
  version: 1.0.0
log:
  level: debug
  logs_path: logs/logs.txt
http:
  bind_ip: localhost
  port: 8080
postgresql:
  host: 0.0.0.0
  port: 5432
  username: root
  password: root
  database: segmentation-service
  max_pool_size: 20