// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Грищенко Владимир",
            "email": "vladimirxsky@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/reports": {
            "post": {
                "description": "Возвращает csv-строку, представляющую собой csv-отчёт,\nсодержащий столбцы ` + "`" + `user_id` + "`" + `, ` + "`" + `segment_name` + "`" + `, ` + "`" + `start_date` + "`" + `,\n` + "`" + `end_date` + "`" + `, обозначающие идентификатор пользователя,\nнаименование сегмента, дату добавления пользователя в сегмент и\nдату выхода пользователя из сегмента соответственно. Строки отчёта\nотсортированы в порядке возрастания по дате добавления пользователя в сегмент.\n\nВ результате выполнения запроса формируется файл и устанавливается заголовок ответа\n` + "`" + `Content-Disposition` + "`" + `, поэтому результат выполнения запроса необходимо скачать.",
                "tags": [
                    "reports"
                ],
                "summary": "Получить отчёт в формате csv",
                "responses": {
                    "200": {
                        "description": "Структура, содержащая дату формирования отчёта и отчёт в виде csv-строки",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.MakeReportResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrReportValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/segments": {
            "get": {
                "description": "Возвращает список всех сегментов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Получить список всех сегментов",
                "responses": {
                    "200": {
                        "description": "Список всех сегментов",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.GetAllSegmentsResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrSegmentValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт сегмент на основе информации в теле запроса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Создать сегмент",
                "parameters": [
                    {
                        "description": "Структура с информацией о создаваемом сегменте",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_service.SegmentCreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Наименование созданного сегмента",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrSegmentValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/segments/{name}": {
            "get": {
                "description": "Возвращает информацию о сегменте с указанным именем",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Получить сегмент с указанным именем",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Наименование сегмента",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сегмент с указанным именем",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.GetSegmentByNameResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrSegmentValidationError"
                        }
                    },
                    "404": {
                        "description": "Сегмент с указанным именем не был найден",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrSegmentNotFound"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет сегмент с указанным именем из системы.\nВ случае, если на момент совершения запроса в этот\nсегмент входят какие-либо пользователи, они автоматически\nвыйдут из данного сегмента.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Удалить сегмент с указанным именем",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Наименование сегмента",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успехе",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.DeleteSegmentByNameResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrSegmentValidationError"
                        }
                    },
                    "404": {
                        "description": "Сегмент с указанным именем не был найден",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrSegmentNotFound"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "Возвращает список абсолютно всех пользователей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить список всех пользователей",
                "responses": {
                    "200": {
                        "description": "Список всех пользователей",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.GetAllUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт пользователя на основе информации в теле запроса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "Структура с информацией о создаваемом пользователе",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_service.UserCreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Идентификатор созданного пользователя",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.UserCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/addUserToSegments": {
            "post": {
                "description": "Добавляет пользователя с указанным ID в указанные сегменты",
                "tags": [
                    "users"
                ],
                "summary": "Добавить пользователя в сегменты",
                "parameters": [
                    {
                        "description": "Структура, содержащая ID пользователя и наименование сегментов, в которые необходимо добавить пользователя. Поле ` + "`" + `end_date` + "`" + ` у сегмента является опциональным, и, если не  установлено, сигнализирует о том, что время выхода пользователя из сегмента не определено (пока сегмент  не будет удалён или пользователь не будет удалён из этого сегмента)",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.AddUserToSegmentsInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успехе",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.AddUserToSegmentsResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserValidationError"
                        }
                    },
                    "404": {
                        "description": "Пользователь с указанным ID не был найден или некоторые из указанных сегментов не существуют",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserNotFound"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/deleteUserFromSegments": {
            "post": {
                "description": "Удаляет пользователя с указанным ID из указанных сегментов",
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя из сегментов",
                "parameters": [
                    {
                        "description": "Структура, содержащая ID пользователя и наименования сегментов, из которых пользователя необходимо удалить",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.DeleteUserFromSegmentsInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успехе",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.DeleteUserFromSegmentsResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса, может возникать, если пользователь не входит в указанные сегменты",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserValidationError"
                        }
                    },
                    "404": {
                        "description": "Пользователь с указанным ID не был найден или некоторые из указанных сегментов не существуют",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserNotFound"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/withSegments": {
            "get": {
                "description": "Возвращает список всех пользователей, включая список активных для каждого пользователя сегментов на момент совершения запроса",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить список всех пользователей, включая их сегменты",
                "responses": {
                    "200": {
                        "description": "Список пользователей с их активными сегментами",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.GetAllUsersWithSegmentsResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "description": "Возвращает пользователя с указанным ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь с указанным ID",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.GetUserByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserValidationError"
                        }
                    },
                    "404": {
                        "description": "Пользователь с указанным ID не был найден",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserNotFound"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/withSegments": {
            "get": {
                "description": "Возвращает пользователя с указанным ID, включая в тело ответа список сегментов, в которые пользователь входит на момент совершения запроса",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя с его сегментами по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь с его активными сегментами",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.GetUserByIDWithSegmentsResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных запроса",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserValidationError"
                        }
                    },
                    "404": {
                        "description": "Пользователь с указанным ID не был найден",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrUserNotFound"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/avito-rest-api_internal_error.ErrInternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "avito-rest-api_internal_entity.Segment": {
            "type": "object",
            "properties": {
                "is_deleted": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "AVITO_MUSIC_SERVICE"
                },
                "segment_id": {
                    "type": "integer",
                    "example": 43
                }
            }
        },
        "avito-rest-api_internal_entity.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 26
                },
                "is_deleted": {
                    "type": "boolean",
                    "example": false
                },
                "lastname": {
                    "type": "string",
                    "example": "Иванов"
                },
                "name": {
                    "type": "string",
                    "example": "Михаил"
                },
                "sex": {
                    "description": "Пол, 0 - мужской, 1 - женский",
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ],
                    "example": 0
                },
                "sex_text": {
                    "type": "string",
                    "enum": [
                        "мужской",
                        "женский"
                    ],
                    "example": "мужской"
                },
                "user_id": {
                    "type": "integer",
                    "example": 16
                }
            }
        },
        "avito-rest-api_internal_entity.UserSegmentInformation": {
            "type": "object",
            "properties": {
                "end_date": {
                    "description": "Дата выхода пользователя из сегмента",
                    "type": "string",
                    "example": ""
                },
                "information_id": {
                    "description": "ID записи в ассоциативной таблице, связывающей пользователей с сегментами",
                    "type": "integer",
                    "example": 179
                },
                "name": {
                    "description": "Наименование сегмента",
                    "type": "string",
                    "example": "AVITO_MUSIC_SERVICE"
                },
                "segment_id": {
                    "description": "ID сегмента",
                    "type": "integer",
                    "example": 43
                },
                "start_date": {
                    "description": "Дата добавления пользователя в сегмент",
                    "type": "string",
                    "example": "15:27:32 01.09.2023"
                },
                "user_id": {
                    "description": "ID пользователя, который входит в сегмент",
                    "type": "integer",
                    "example": 16
                }
            }
        },
        "avito-rest-api_internal_entity.UserWithSegments": {
            "type": "object",
            "properties": {
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/avito-rest-api_internal_entity.UserSegmentInformation"
                    }
                },
                "user": {
                    "$ref": "#/definitions/avito-rest-api_internal_entity.User"
                }
            }
        },
        "avito-rest-api_internal_error.ErrInternalServerError": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "originErrorText": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "avito-rest-api_internal_error.ErrReportValidationError": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "originErrorText": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "avito-rest-api_internal_error.ErrSegmentNotFound": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "originErrorText": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "avito-rest-api_internal_error.ErrSegmentValidationError": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "originErrorText": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "avito-rest-api_internal_error.ErrUserNotFound": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "originErrorText": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "avito-rest-api_internal_error.ErrUserValidationError": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "originErrorText": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "avito-rest-api_internal_service.SegmentCreateInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Имя сегмента",
                    "type": "string",
                    "example": "AVITO_MUSIC_SERVICE"
                },
                "percentage": {
                    "description": "Необязательное поле, процент пользователей, которое автоматически войдёт в сегмент при его создании",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 57
                }
            }
        },
        "avito-rest-api_internal_service.UserCreateInput": {
            "type": "object",
            "required": [
                "age",
                "lastname",
                "name",
                "sex"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 26
                },
                "lastname": {
                    "type": "string",
                    "example": "Иванов"
                },
                "name": {
                    "type": "string",
                    "example": "Михаил"
                },
                "sex": {
                    "description": "Пол, 0 - мужской, 1 - женский",
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ],
                    "example": 0
                }
            }
        },
        "internal_controller_http_v1.AddUserToSegmentsInput": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer",
                    "example": 16
                },
                "segments": {
                    "description": "Сегменты, в которые необходимо добавить пользователя",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "end_date": {
                                "description": "Необязательное поле, если отсутствует, значит дата выхода пользователя из сегмента не определена",
                                "type": "string",
                                "example": "10:00:00 25.09.2023"
                            },
                            "name": {
                                "description": "Наименование сегмента, в который необходимо добавить пользователя",
                                "type": "string",
                                "example": "AVITO_MUSIC_SERVICE"
                            }
                        }
                    }
                }
            }
        },
        "internal_controller_http_v1.AddUserToSegmentsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user 16 was successfully added to the segments"
                }
            }
        },
        "internal_controller_http_v1.CreateResponse": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "AVITO_MUSIC_SERVICE"
                }
            }
        },
        "internal_controller_http_v1.DeleteSegmentByNameResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "successfully deleted segment \"AVITO_MUSIC_SERVICE\""
                }
            }
        },
        "internal_controller_http_v1.DeleteUserFromSegmentsInput": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer",
                    "example": 16
                },
                "segments": {
                    "description": "Сегменты, из которых необходимо удалить пользователя",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "name": {
                                "description": "Наименование сегмента",
                                "type": "string",
                                "example": "AVITO_MUSIC_SERVICE"
                            }
                        }
                    }
                }
            }
        },
        "internal_controller_http_v1.DeleteUserFromSegmentsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user 179 was successfully removed from segments"
                }
            }
        },
        "internal_controller_http_v1.GetAllSegmentsResponse": {
            "type": "object",
            "properties": {
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/avito-rest-api_internal_entity.Segment"
                    }
                }
            }
        },
        "internal_controller_http_v1.GetAllUsersResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/avito-rest-api_internal_entity.User"
                    }
                }
            }
        },
        "internal_controller_http_v1.GetAllUsersWithSegmentsResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/avito-rest-api_internal_entity.UserWithSegments"
                    }
                }
            }
        },
        "internal_controller_http_v1.GetSegmentByNameResponse": {
            "type": "object",
            "properties": {
                "segment": {
                    "$ref": "#/definitions/avito-rest-api_internal_entity.Segment"
                }
            }
        },
        "internal_controller_http_v1.GetUserByIDResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/avito-rest-api_internal_entity.User"
                }
            }
        },
        "internal_controller_http_v1.GetUserByIDWithSegmentsResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/avito-rest-api_internal_entity.UserWithSegments"
                }
            }
        },
        "internal_controller_http_v1.MakeReportResponse": {
            "type": "object",
            "properties": {
                "report": {
                    "description": "Отчёт в виде csv-строки с разделителями \",\" и символом перехода на новую строку \"\\n\"",
                    "type": "string"
                },
                "report_date": {
                    "description": "Дата формирования отчёта",
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.UserCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 26
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Сервис по работе с сегментами",
	Description:      "Сервис предоставляет функционал для работы с сегментами и пользователями для целей аналитики",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
